"""empty message

Revision ID: 3068223c903f
Revises: 
Create Date: 2018-08-01 14:54:39.704842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3068223c903f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mtag')
    op.drop_table('bi_all_asset_received')
    op.drop_table('test01')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test01',
    sa.Column('a', mysql.INTEGER(display_width=1), autoincrement=False, nullable=False),
    sa.Column('b', mysql.INTEGER(display_width=1), autoincrement=False, nullable=False),
    sa.Column('c', mysql.INTEGER(display_width=1), autoincrement=False, nullable=False),
    sa.Column('d', mysql.INTEGER(display_width=1), autoincrement=False, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bi_all_asset_received',
    sa.Column('credit_no', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('product_type', mysql.INTEGER(display_width=2), autoincrement=False, nullable=True),
    sa.Column('business_type', mysql.INTEGER(display_width=2), server_default=sa.text("'2'"), autoincrement=False, nullable=True),
    sa.Column('product', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('manager_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cost_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('fact_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('write_off_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('plan_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('left_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('overdue_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('bad_debt_amount_e2', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('credit_no'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('mtag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('desc', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('createTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('openId', mysql.VARCHAR(length=128), server_default=sa.text("'0'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_comment='标签',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('user')
    # ### end Alembic commands ###
