"""empty message

Revision ID: f81983b9c140
Revises: 3068223c903f
Create Date: 2018-08-01 15:00:33.757532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81983b9c140'
down_revision = '3068223c903f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('createTime', sa.TIME(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'createTime')
    # ### end Alembic commands ###
